# These options apply to how the script will operate.
script_options:
  LOG_TRADES: True
  LOG_FILE: 'trades.txt'

# Data extraction parameters for modeling (max = 1000)
model_options:
  NO_DATA: 1000

# These parameters apply for the modern machine learning models
ml_options:
  TRAIN_SIZE: 0.9
  NEURONS: 128
  DROPOUT: 0.15
  N_STEPS_IN: 1
  N_STEPS_OUT: 32
  EPOCH: 1000
  N_FEATURES: 4
  VERBOSE: 2

# These options apply to the trading methods the script executes
trading_options:
  # select your base currency to use for trading (trade for example USDT pairs)
  PAIR_WITH: USDT
  # trading timeframe
  WORK_TIMEFRAME: 1h
  TRAIN_TIMEFRAME: 1d
  # Name of custom tickers list
  TICKERS_LIST: 'tickers.txt'