# Data extraction parameters for modeling (max = 1000)
model_options:
  NO_DATA: 1000
  ML_MODEL: 'LSTM'
  # Fractional Differentiation weight. 0 for no differentiation at all and 1 for whole integer differentiation
  WEIGHT: 0.9625

# Date of the model to load for forecasting
model_parameters_options:
  MODEL_DATE: '2022714'

# Date of the scaler model to invert model and plot
scaler_parameters_options:
  SCALER_DATE: '2022714'

# Portfolio Options (degree of memory (0: full memory about past data, 1001: only memory about forecasts))
portfolio_options:
  PORTFOLIO_MEMORY: 1000
  #optimization type: could be OPTIMAL_SHARPE, MINIMUM_VARIANCE or CAPITAL_MARKET_LINE (CAPM):
  OPTIMIZATION_TYPE: 'CAPITAL_MARKET_LINE'
  VAR_CONFIDENCE: 0.95

# These parameters apply for the modern machine learning models
ml_options:
  TRAIN_SIZE: 0.75
  NEURONS: 128
  DROPOUT: 0.15
  N_STEPS_IN: 1
  N_STEPS_OUT: 100
  EPOCH: 250
  N_FEATURES: 4
  VERBOSE: 2

# These options apply to the trading methods the script executes
trading_options:
  # select your base currency to use for trading (trade for example USDT pairs)
  PAIR_WITH: USDT
  # trading timeframe
  WORK_TIMEFRAME: 1d
  TRAIN_TIMEFRAME: 1d
  # Name of custom tickers list
  TICKERS_LIST: 'tickers.txt'